### ISSUE TITLE
readme, comments and naming.

### ISSUE THREAD

**Issue by 23inhouse** [waterlink/rebecca#8]
I'm reading the library for the first time so I'm taking notes on what I found confusing from a fresh perspective.

README:
- [x] It might be nice to recommend importing the package as `bec` or something `rebecca` is a bit long. Or `psql` it might look nice to read it like this: `psql.Get(25, p)` it would like even nicer as `Get(p, 25)`

Context:
- Possibly rename it to `Clause` (extracted to #19)
- [x] It would be good to have a link to the context implementation and possibly a short note about why there is an interface or to try to remove the interface.
- [x] Maybe rename `Skip` to `Offset` with a note that in mongoDB it would be called skip or have both.

Rebecca:
- [x] possibly reorder the functions by select, insert/update and delete
- [x] Get might be easier to read as `Get(p, 25)` this way `Get` matches other functions with the record first.

Transaction:
- [x] It might be good to put the `transaction` file into `rebecca` or separate the shared unexported functions like `save` into it's own file.

Driver:
- [x] I wasn't expecting `driver` ( in `driver.Get(...)`) to be a var defined in a different file in the rebecca package.
- [x] What do you think about moving driver into a package directory and putting pg in there too?

Auto:
- [x] I'm not sure if auto is that useful. For someone reading the library for the first time, it's extra stuff to read.
- Would it be useful to have an `Execute` function? (extracted to #20)

**Comment by waterlink** [comment]
@23inhouse Not sure about `Clause`. Maybe something else comes up to your mind?

**Comment by waterlink** [comment]
@23inhouse I have fixed small fries :) Two mentioned issues, that are left, I have extracted to #19 and #20. Effectively making this issue resolved.

Closing.
